from django.urls import path
from django.views.generic.base import RedirectView

from .api_views import (
    api_dns,
    api_health,
    api_http_check,
    api_ip,
    api_not_found,
    api_punycode,
    api_redirects,
    api_security_headers,
    api_subnet,
    api_tls,
)

from .views import (
    about,
    apple_touch_icon,
    favicon_48,
    favicon_96,
    favicon_ico,
    favicon_png,
    browser_check,
    canvas_fingerprint,
    client_ip,
    dns_lookup,
    dnssec_checker,
    developers,
    domain_age,
    download_time_calculator,
    email_dns_checker,
    file_hash,
    glossary,
    health,
    home,
    hostname_lookup,
    http_headers,
    icon_192,
    icon_512,
    icon_source,
    ip_address_checker,
    ip_lookup,
    location,
    learn,
    learn_article,
    meta_tags_checker,
    network,
    password_strength,
    privacy_check,
    punycode_converter,
    request_headers,
    rdap_lookup,
    redirect_checker,
    reverse_dns,
    robots_txt,
    screen_resolution,
    security_headers,
    server_headers,
    speed_test_download,
    sitemap_checker,
    sitemap_xml,
    site_webmanifest,
    ssl_checker,
    subnet_calculator,
    tools,
    url_parser,
    user_agent,
    webgl,
    website_status,
    robots_txt_checker,
)


urlpatterns = [
    path("", home, name="home"),
    path("about/", about, name="about"),
    path("developers/", developers, name="developers"),
    path(
        "developers/api/",
        RedirectView.as_view(url="/developers/", permanent=True),
        name="developers-api",
    ),
    path("api/v1/health", api_health, name="api-v1-health"),
    path("api/v1/http-check", api_http_check, name="api-v1-http-check"),
    path("api/v1/dns", api_dns, name="api-v1-dns"),
    path("api/v1/redirects", api_redirects, name="api-v1-redirects"),
    path("api/v1/tls", api_tls, name="api-v1-tls"),
    path(
        "api/v1/security-headers",
        api_security_headers,
        name="api-v1-security-headers",
    ),
    path("api/v1/ip", api_ip, name="api-v1-ip"),
    path("api/v1/subnet", api_subnet, name="api-v1-subnet"),
    path("api/v1/punycode", api_punycode, name="api-v1-punycode"),
    path("api/v1", api_not_found, {"unmatched_path": ""}),
    path("api/v1/", api_not_found, {"unmatched_path": ""}),
    path("api/v1/<path:unmatched_path>", api_not_found, name="api-v1-not-found"),
    path("tools/", tools, name="tools"),
    path("user-agent/", user_agent, name="user-agent"),
    path("browser-check/", browser_check, name="browser-check"),
    path("screen-resolution/", screen_resolution, name="screen-resolution"),
    path("http-headers/", http_headers, name="http-headers"),
    path("privacy-check/", privacy_check, name="privacy-check"),
    path("webgl/", webgl, name="webgl"),
    path(
        "canvas-fingerprint/",
        canvas_fingerprint,
        name="canvas-fingerprint",
    ),
    path("ip-lookup/", ip_lookup, name="ip-lookup"),
    path("ip-address-checker/", ip_address_checker, name="ip-address-checker"),
    path("dns-lookup/", dns_lookup, name="dns-lookup"),
    path("dnssec-checker/", dnssec_checker, name="dnssec-checker"),
    path("email-dns-checker/", email_dns_checker, name="email-dns-checker"),
    path("reverse-dns/", reverse_dns, name="reverse-dns"),
    path("hostname-lookup/", hostname_lookup, name="hostname-lookup"),
    path("ssl-checker/", ssl_checker, name="ssl-checker"),
    path("website-status/", website_status, name="website-status"),
    path("redirect-checker/", redirect_checker, name="redirect-checker"),
    path("server-headers/", server_headers, name="server-headers"),
    path("security-headers/", security_headers, name="security-headers"),
    path("robots-txt-checker/", robots_txt_checker, name="robots-txt-checker"),
    path("sitemap-checker/", sitemap_checker, name="sitemap-checker"),
    path("meta-tags-checker/", meta_tags_checker, name="meta-tags-checker"),
    path("subnet-calculator/", subnet_calculator, name="subnet-calculator"),
    path("password-strength/", password_strength, name="password-strength"),
    path("punycode-converter/", punycode_converter, name="punycode-converter"),
    path("url-parser/", url_parser, name="url-parser"),
    path("file-hash/", file_hash, name="file-hash"),
    path("rdap-lookup/", rdap_lookup, name="rdap-lookup"),
    path("domain-age/", domain_age, name="domain-age"),
    path(
        "download-time-calculator/",
        download_time_calculator,
        name="download-time-calculator",
    ),
    path(
        "speed-test/download/",
        speed_test_download,
        name="speed-test-download",
    ),
    path("robots.txt", robots_txt, name="robots"),
    path("sitemap.xml", sitemap_xml, name="sitemap"),
    path("learn/", learn, name="learn"),
    path("learn/<slug:slug>/", learn_article, name="learn-article"),
    path("glossary/", glossary, name="glossary"),
    path("health", health, name="health"),
    path("headers", request_headers, name="headers"),
    path("ip", client_ip, name="ip"),
    path("location", location, name="location"),
    path("network", network, name="network"),
    path("icon-source.png", icon_source, name="icon-source"),
    path("favicon.ico", favicon_ico, name="favicon-ico"),
    path("favicon-48.png", favicon_48, name="favicon-48"),
    path("favicon-96.png", favicon_96, name="favicon-96"),
    path("apple-touch-icon.png", apple_touch_icon, name="apple-touch-icon"),
    path("icon-192.png", icon_192, name="icon-192"),
    path("icon-512.png", icon_512, name="icon-512"),
    path("site.webmanifest", site_webmanifest, name="site-webmanifest"),
    path("favicon.png", favicon_png, name="favicon-png"),

]
