from django.urls import path

from .views import (
    browser_check,
    canvas_fingerprint,
    client_ip,
    dns_lookup,
    download_time_calculator,
    health,
    home,
    hostname_lookup,
    http_headers,
    ip_address_checker,
    ip_lookup,
    location,
    network,
    password_strength,
    privacy_check,
    punycode_converter,
    request_headers,
    reverse_dns,
    robots_txt,
    screen_resolution,
    server_headers,
    sitemap_xml,
    ssl_checker,
    subnet_calculator,
    tools,
    user_agent,
    webgl,
    website_status,
)


urlpatterns = [
    path("", home, name="home"),
    path("tools/", tools, name="tools"),
    path("user-agent/", user_agent, name="user-agent"),
    path("browser-check/", browser_check, name="browser-check"),
    path("screen-resolution/", screen_resolution, name="screen-resolution"),
    path("http-headers/", http_headers, name="http-headers"),
    path("privacy-check/", privacy_check, name="privacy-check"),
    path("webgl/", webgl, name="webgl"),
    path(
        "canvas-fingerprint/",
        canvas_fingerprint,
        name="canvas-fingerprint",
    ),
    path("ip-lookup/", ip_lookup, name="ip-lookup"),
    path("ip-address-checker/", ip_address_checker, name="ip-address-checker"),
    path("dns-lookup/", dns_lookup, name="dns-lookup"),
    path("reverse-dns/", reverse_dns, name="reverse-dns"),
    path("hostname-lookup/", hostname_lookup, name="hostname-lookup"),
    path("ssl-checker/", ssl_checker, name="ssl-checker"),
    path("website-status/", website_status, name="website-status"),
    path("server-headers/", server_headers, name="server-headers"),
    path("subnet-calculator/", subnet_calculator, name="subnet-calculator"),
    path("password-strength/", password_strength, name="password-strength"),
    path("punycode-converter/", punycode_converter, name="punycode-converter"),
    path(
        "download-time-calculator/",
        download_time_calculator,
        name="download-time-calculator",
    ),
    path("robots.txt", robots_txt, name="robots"),
    path("sitemap.xml", sitemap_xml, name="sitemap"),
    path("health", health, name="health"),
    path("headers", request_headers, name="headers"),
    path("ip", client_ip, name="ip"),
    path("location", location, name="location"),
    path("network", network, name="network"),
]
